Feature 59 stringcompare adjustment
amos-ws16/amos-ws16-arrowjs pull request #31
Opened 2016-11-27 15:52 UTC by dn0912

2016-11-27 16:10 UTC, oesse reviewed
Da kann noch ein bisschen augeräumt werden.

2016-11-27 16:10 UTC, oesse commented on lib/plugins/similar-context-plugin.js
> +  if ((typeof sString1 !== 'undefined') || (typeof sString2 !== 'undefined')) {
Besser Fehlerfall (mit throw) zuerst checken, da danach kein else mehr nötig ist
if (failed) { throw new Error() }
doSomething()

2016-11-27 16:10 UTC, oesse commented on lib/plugins/similar-context-plugin.js
> +  if ((typeof sString1 !== 'undefined') || (typeof sString2 !== 'undefined')) {
Außerdem checkt utils.isValidString() ob es ein richtiger String ist. Daher:
if (!isValidString(sString1) || !isValidString(sString2) {
  throw new Error('...')
}

2016-11-27 16:10 UTC, oesse commented on lib/plugins/similar-context-plugin.js
> +  if ((extractKeywords === false)) {
Warum Extraklammern um if (())?

2016-11-27 16:10 UTC, oesse commented on lib/plugins/similar-context-plugin.js
> +  if ((extractKeywords === false)) {
If-else vereinfachen indem du erst checkst:
if (typeof extractKeywords !== 'boolean') { throw }
Dann nurnoch
if (extractKeywords) {
  return ...
}
// Kein else weil du ja schon returned hast

2016-11-27 16:10 UTC, oesse commented on lib/utils.js
>      throw new Error(`${sString} is not a valid string`)
Lieber schreiben was die Erwartung ist als was gefunden wurde oder beides. D.h. 'String expected, found ${sString}'

2016-11-27 16:10 UTC, oesse commented on lib/utils.js
> +    throw new Error(`Empty input`)
Siehe oben: 'String must not be empty' oder 'Non-empty string expected'

2016-11-27 16:10 UTC, oesse commented on test/plugins/similar-context-test.js
>      buster.assert.near(1.0, result, 0)
3. Argument von near() ist eine Toleranz, d.h. 0 macht keinen Sinn (das wäre exakt ===). Lieber 1.0e-3 oder sowas verwenden

2016-11-27 16:29 UTC, jhuenges commented on test/plugins/similar-context-test.js
>      buster.assert.near(1.0, result, 0)
Aber es sollte ja 1.0 bei raus kommen

2016-11-27 16:33 UTC, oesse commented on test/plugins/similar-context-test.js
>      buster.assert.near(1.0, result, 0)
In dem Fall mag es klappen, weil der Algorithmus exakt 1.0 zurück gibt. Wenn der Algo aber z.b. 0.99999 zurück gibt wird der Test fehlschlagen, wobei das auch nur Rundungsfehler sein könnte.

2016-11-27 17:22 UTC, oesse commented on test/plugins/similar-context-test.js
>      buster.assert.near(1.0, result, 0)
Es kommt immer drauf an, was man testen möchte. Wenn es genau exakt 1.0 sein muss, dann sollte man buster.assert.equals() oder buster.assert.same() verwenden. Wenn es nur um 'nach Rundung sollte es so nah wie möglich an 1.0 sein' sein sollte, dann near() mit einer sinnvollen Toleranz

2016-11-27 20:56 UTC, oesse commented on lib/plugins/similar-context-plugin.js
> +  }
noch weniger doppelt:
if (extractKeywords) {
  sString1 = getKeywords(sString1)
  sString2 = getKeywords(sString2)
}
return stringSimilarity.compareTwoStrings(sString1, sString2)

2016-11-28 16:12 UTC, jhuenges requested changes

2016-11-28 16:12 UTC, jhuenges commented on lib/plugins/similar-context-plugin.js
> + * @param keywordParam - object with attribute extractKeywords as parameter for extracting the keywords (true - extract keyword before calculating similarity score, false - whithout extraction)
Das ist nur noch `params`

2016-11-28 16:32 UTC, jhuenges approved these changes

2016-11-29 04:49 UTC, fabian247 requested changes
Zeilen 11 und 12 in jsdoc: 
@param file ersetzen durch sString1 und @param task ersetzen durch sString2

2016-11-29 21:00 UTC, merged