Reworked the input scheme.
amos-ws16/amos-ws16-arrowjs pull request #32
Opened 2016-11-27 18:25 UTC by yvFischer

Guckt euch das mal noch mal an, ich habe jetzt (wie Actano das vorgeschlagen hat) einen Bereich 'content' und einen Bereich 'metadata' erstellt. Meint ihr in den Metadatabereich müsste noch mehr rein?

2016-11-28 16:34 UTC, jhuenges requested changes
Ansonsten: LGTM

2016-11-28 16:34 UTC, jhuenges commented on docs/rest-api.md
> +      "created_on": "(required) number",
Ich fände `created_at` besser

2016-11-28 16:34 UTC, jhuenges commented on docs/rest-api.md
> +        "created_on": "(required) number",
Same

2016-11-28 16:34 UTC, jhuenges commented on docs/rest-api.md
> +        "last_updated_on": "number",
Hier fände ich `last_updated_at` besser

2016-11-28 21:24 UTC, oesse commented on docs/rest-api.md
> +      "created_on": "(required) number",
"(required) unix timestamp" statt "(required) number"

2016-11-28 21:24 UTC, oesse commented on docs/rest-api.md
> +        "created_on": "(required) number",
number -> unix timestamp

2016-11-28 21:24 UTC, oesse commented on docs/rest-api.md
> +        "wheight": "(required) float"
weight?

2016-11-28 21:24 UTC, oesse commented on docs/rest-api.md
> +  "metadata": {
Soll metadata die Konfiguration sein?

2016-11-29 06:53 UTC, fabian247 commented on docs/rest-api.md
> +        "wheight": "(required) float"
Das ist vermutlich dafür gedacht, wenn wir den Aggregator auch konfigurieren wollen. Machen wir aktuell aber noch nicht.
Ich dachte eher hier soll sowas rein:
`"name": {
      use: "plugin-name",
      inputs: [input1, input2[].item],
      params: { "name of parameter for plugin-name": "value" }
    }`

2016-11-29 06:58 UTC, fabian247 commented on docs/rest-api.md
> +  "metadata": {
Die Funktion postApiScore liest doch den Block "config" aus, oder? Dann brauchen wir den auch im Input. Oder verstehe ich hier was falsch? 
Ich finde das sollte "config" statt metadata heißen.

2016-11-29 07:00 UTC, oesse commented on docs/rest-api.md
> +  "metadata": {
Ja, wenn wir das erlauben wollen (was ja noch nicht klar ist), dass man per REST eine Konfiguration mitschickt, dann sollte sie config heißen. Ansonsten müssen wir den Part rausnehmen aus dem Schema

2016-11-29 07:25 UTC, yvFischer commented on docs/rest-api.md
> +  "metadata": {
Ja genau, das hatte Actano so vorgeschlagen und ich wollte mal gucken, was ihr davon haltet. Meint ihr wir sollen das so übernehmen oder das doch nur per config Datei machen? Vielleicht nehme ich das erstmal wieder raus und wir bequatschen das zusammen am Donnerstag

2016-11-29 09:24 UTC, jhuenges approved these changes

2016-11-29 09:49 UTC, oesse approved these changes
LGTM

2016-11-29 21:00 UTC, merged