Server-Dateien aus Engine gelöscht
amos-ws16/amos-ws16-arrowjs pull request #53
Opened 2016-12-11 15:26 UTC by simonschwan

- alle Dateien gelöscht, die zum Server gehören und daher nicht mehr in die Engine gehören
- Deployment gelöscht (dies muss nun auch im Server funktionieren)
- Docs zum Server gelöscht

2016-12-11 16:10 UTC, oesse requested changes
In der package.json muss noch die Datei angegeben werden, die bei require('arrow') geladen wird, also der main entry point.
Siehe: https://docs.npmjs.com/files/package.json#main

2016-12-11 16:10 UTC, oesse commented on package.json
>      "body-parser": "^1.15.2",
`body-parser` gehört auch mit zu express und kann in der engine entfernt werden

2016-12-11 17:10 UTC, simonschwan commented
@oesse 
Habe deine Änderungen angepasst. body-parser habe ich wohl übersehen. Danke!
Als Einstiegspunkt habe ich jetzt den score-manager gewählt

2016-12-12 17:09 UTC, fabian247 commented
Sind hier jetzt alle Changes drin? 
Schaut nochmal wer drüber?

2016-12-13 10:03 UTC, closed without merging