Feature 70 test case auswertung
amos-ws16/amos-ws16-arrowjs pull request #55
Opened 2016-12-11 18:17 UTC by kevinstyp

Der Feature-30 branch kommt durch diesen PullRequest auch wieder in unsere API :)

2016-12-11 18:18 UTC, kevinstyp commented
Ich musste leider in der "test-cases-run.js" am ende mit einem 'setTimeout()' arbeiten, da supertest die Tests leider asynchron ausführt und sonst noch keine Hits recorded wurden bevor man auf die asynchronen Tests wartet :/

2016-12-11 22:32 UTC, dn0912 commented
testcase-test vor der Bewertung eingefügt (Credits gehen an @jhuenges :D) und besser Darstellung der Ergebnisse in der Konsole

2016-12-12 16:31 UTC, fabian247 commented on test/test-cases/test-cases-run.js
> +  head: ['TestCase file', 'größter Index', 'größter Score'],
"größter Index" ist nicht so aussagekräftig. Das hört sich für mich eher so an wie Größe des Arrays. 
Evtl. als Spalte ganz rechts neben dem Score anzeigen und nur "Index" nennen.

2016-12-12 20:23 UTC, jhuenges requested changes

2016-12-12 20:23 UTC, jhuenges commented on test/test-cases/test-cases-run.js
> +*@param
das `@param` kann weg

2016-12-13 12:00 UTC, jhuenges approved these changes

2016-12-13 15:18 UTC, merged