Feature 74 input filter
amos-ws16/amos-ws16-arrowjs pull request #57
Opened 2016-12-12 18:40 UTC by jhuenges

Added support for pipes, see user guide

2016-12-13 06:37 UTC, oesse approved these changes
LGTM! Sehr nice ;-)

2016-12-13 06:37 UTC, oesse commented on test/pipes/to-lower-case-test.js
> +const pipe = require('../../lib/pipes/to-lower-case.js')
'.js' kann weg

2016-12-13 06:37 UTC, oesse commented on test/pipes/to-upper-case-test.js
> +const pipe = require('../../lib/pipes/to-upper-case.js')
'.js' kann weg

2016-12-13 06:37 UTC, oesse commented on test/pipes/trim-left-test.js
> +const pipe = require('../../lib/pipes/trim-left.js')
'.js' kann weg

2016-12-13 06:37 UTC, oesse commented on test/pipes/trim-right-test.js
> +const pipe = require('../../lib/pipes/trim-right.js')
'.js' kann weg

2016-12-13 06:37 UTC, oesse commented on test/pipes/trim-test.js
> +const pipe = require('../../lib/pipes/trim.js')
'.js' kann weg

2016-12-13 15:11 UTC, fabian247 requested changes
Sieht gut aus, bis auf die eine Beschreibung im user-guide

2016-12-13 15:11 UTC, fabian247 commented on docs/user-guide.md
> +You can choose from these Aggregators:
choose from these Pipes

2016-12-13 20:32 UTC, fabian247 reviewed
Beim mergen ist was schief gelaufen. Sonst top.
Kann ich mir morgen früh nochmal anschauen... Wäre aber gut zu wissen welcher branch stimmt... jeweils head oder dev oder beides?

2016-12-13 20:32 UTC, fabian247 commented on docs/user-guide.md
> +>>>>>>> dev
Hier ist beim mergen was schief gelaufen. Ich nehme an es gilt dev, oder?

2016-12-13 20:32 UTC, fabian247 commented on docs/user-guide.md
> +>>>>>>> dev
Auch ein merge confict. Was gilt hier? Scheint irgendwie beides nicht zu passen... Oder gilt beides zusammen? Das scheint mir am ehesten Sinn zu machen.

2016-12-14 06:25 UTC, fabian247 approved these changes

2016-12-14 06:40 UTC, merged