Chatverlauf aus Slack
amos-ws16/amos-ws16-arrowjs pull request #69
Opened 2017-01-09 22:17 UTC by simonschwan

Ich habe jetzt den Chatverlauf in die Default API-Spezifikation aufgenommen.
Es gibt noch zusätzlich interessante Attribute für Attachements und hochgeladene Dateien. Da wir ja hochgeladene Dateien eh schon behandeln, habe ich sie nicht in den Chatverlauf reingenommen.
Was sagt ihr?

2017-01-10 12:24 UTC, jhuenges requested changes

2017-01-10 12:24 UTC, jhuenges commented on docs/rest-api.md
> +            "type": "message",
Vielleicht sollten hier noch die anderen Möglichkeiten aufgelistet werden.

2017-01-10 15:38 UTC, simonschwan reviewed
Ich habe jetzt alles meiner Meinung nach relevanten Typen von messages, die Slack unterstützt in eine Liste gepackt.

Allerdings könnte es sinnvoller und übersichtlicher sein, einfach einen Link zur Slack-API zu geben und zu sagen, das könnt ihr uns alles übergeben und dann können wir nur die Messages untersuchen, die wir implementiert haben und die uns was bringen.

Was sagt ihr?

2017-01-10 15:54 UTC, jhuenges commented
Ist vielleicht sinnvoll.

2017-01-11 11:46 UTC, simonschwan commented
Ich habe jetzt den passenden Link zu der Slack API eingefügt

2017-01-11 16:10 UTC, dn0912 approved these changes

2017-01-11 16:11 UTC, dn0912 commented
LGTM

2017-01-11 16:41 UTC, merged