Feature 79: User Guide
amos-ws16/amos-ws16-arrowjs pull request #71
Opened 2017-01-10 18:30 UTC by jhuenges

Der User Guide enthält jetzt Informationen wie man die Engine über npm installiert und benutzt

2017-01-10 18:54 UTC, dn0912 requested changes
Siehe Kommentare
Vielleicht schaut sich das noch ein Zweiter mit an. :)

2017-01-10 18:54 UTC, dn0912 commented on docs/user-guide.md
> +# Arrow.js - The correlation engine
würde irgendwo "user guide" stehen lassen, da die Start-Webseite die gleiche überschrift hat.

2017-01-10 18:54 UTC, dn0912 commented on docs/user-guide.md
> +#### 4.2.1 Usage
Nummerierung kannst du weglassen da keine weiteren Unterpunkte da sind

2017-01-10 18:54 UTC, dn0912 commented on docs/user-guide.md
> + 1. [Content](#Content)
TOC Links funktionieren nicht, alles in () muss kleingeschrieben werden und genau mit der überschrift übereinstimmen. Leerzeichen mit - ersetzen

2017-01-10 18:54 UTC, dn0912 commented on docs/user-guide.md
> +## 2. Introduction
könntest auch 2. Introduction und 3. Installation irgendwie zusammenfassen, da Einzeiler. Oder frühere Beschreibung behalten. Mehrere Meinungen gefragt :)

2017-01-10 18:54 UTC, dn0912 commented on docs/user-guide.md
> -## 2. Requests
Wollen wir wirklich den Link für den REST Call löschen? Vllt nützlich um API zu testen

2017-01-10 19:02 UTC, merged

2017-01-11 06:56 UTC, jhuenges commented on docs/user-guide.md
> -## 2. Requests
Der Link steht in dem API user guide mit drin