Feature 99 automatic input ids
amos-ws16/amos-ws16-arrowjs pull request #77
Opened 2017-01-24 01:13 UTC by simonschwan

Das mit den Input-IDs funktioniert jetzt. Ich habe es noch nicht in Kombination mit dem Server getestet, da ich erstmal Info brauche, wie die Authentifizierung funktioniert. Aber damit ihr schonmal euren Senf dazu geben könnt und ich das morgen Abend einarbeiten kann, hier schonmal der PullRequest.

Man kann nun über 'idPath' in der config einen Ort angeben, unter dem IDs zu finden sind. Sollten keine IDs in den Objekten bestehen, so werden diese erzeugt und natürlich bei den scores mit zurückgegeben. Das ganze ist freiwillig. Wenn man keinen idPath angibt, dann bekommt man auch keine IDs zurück.

Standardkonfig: idPath: 'tasks[].id'
Dokumentation folgt morgen.

2017-01-24 23:56 UTC, simonschwan commented
Ich habe jetzt die Dokumentation eingefügt und ein paar Beispiele mit dem Server getestet. Also sollte das Feature fertig sein, wenn es keine Änderungswünsche gibt.

2017-01-25 10:41 UTC, jhuenges requested changes

2017-01-25 10:41 UTC, jhuenges commented on docs/user-guide.md
> +This means that if you provide this field in your tasks, the corresponding score will also return the ID. If you, don't insert the ID, then the API will generate and return a random ID:
Das Komm nach "if you" kann weg

2017-01-25 10:41 UTC, jhuenges commented on docs/user-guide.md
> +
Hier fehlt noch was, oder?

2017-01-25 10:41 UTC, jhuenges commented on docs/user-guide.md
> +
Hier auch

2017-01-25 21:45 UTC, oesse reviewed
Ziemlich gut! Da eh noch merge-conflicts zu bearbeiten sind, fände ich die Anpassungen in der Doku von `insertByPath()` noch super.

2017-01-25 21:45 UTC, oesse commented on lib/score-manager.js
> +        // use Date.now() + idx as generated id
Dieser Kommentar ist das gleiche was die folgende Code Zeile sagt, also überflüssig

2017-01-25 21:45 UTC, oesse commented on lib/utils.js
> + * Inserts content into an object by using its path in string format.
Vielleicht noch wichtig: verändert den `object` parameter und gibt nichts zurück. Und: Fügt alle Subobjekte, die auf dem Weg in `path` liegen ein. Beispiel:
```javascript
let object = {}
insertByPath(object, 'a.b.c.d', 'hello')
assert object == { a: { b: { c: { d: 'hello' } } } }
```

2017-01-25 23:26 UTC, jhuenges approved these changes

2017-01-26 01:54 UTC, merged