Increase coverage
amos-ws16/amos-ws16-arrowjs pull request #82
Opened 2017-01-31 16:59 UTC by jhuenges

Endlich!

2017-01-31 17:02 UTC, jhuenges commented
Für die restlichen 0.205% bräuchte ich Hilfe. Ich hab keine Ahnung, wie ich diese Zeile testen soll ...

2017-02-01 17:26 UTC, simonschwan requested changes

2017-02-01 17:26 UTC, simonschwan commented on lib/score-manager.js
> -  if (!plugins) {
Müsste das hier nicht drin bleiben?

2017-02-01 17:26 UTC, simonschwan commented on lib/score-manager.js
> -    if (!plugin.inputs) {
Und das hier auch?
Das sind doch beides Fälle, die eintreffen können, oder?

2017-02-01 17:55 UTC, jhuenges commented on lib/score-manager.js
> -  if (!plugins) {
Ne, hier kann der Fall nicht mehr eintreten. Dadurch das vorher alle Plugins durch `ensureValidInputGroup` gehen. Da wird schon getestet, ob es ein plugins gibt, oder nicht. Und wenn es keine Plugins und keine Input Group und keine Inputs gibt, dann wirft er da den Fehler.

2017-02-01 17:56 UTC, jhuenges commented on lib/score-manager.js
> -    if (!plugin.inputs) {
Siehe oben

2017-02-01 18:12 UTC, merged