Feature 106 compare plugin
amos-ws16/amos-ws16-arrowjs pull request #86
Opened 2017-02-03 13:29 UTC by simonschwan

- compare-numbers-plugin implementiert
- Dokumentation angepasst
- Beispiele für pipes, die jetzt sinnvoll sind, da es das neue Plugin gibt

2017-02-03 15:36 UTC, jhuenges requested changes
Noch ein paar Kleinigkeiten

2017-02-03 15:36 UTC, jhuenges commented on docs/examples/pipes/day-of-month.md
> +
Hier fehlt noch was

2017-02-03 15:36 UTC, jhuenges commented on test/plugins/compare-numbers-plugin-test.js
> +  'throw an exception if not known operator': function () {
should throw an exception

2017-02-03 15:36 UTC, jhuenges commented on test/plugins/compare-numbers-plugin-test.js
> +  '= works as expected': function () {
Die Beschreibungen sollten immer mit "should" anfangen. Ist aber nicht ganz so wild

2017-02-06 13:09 UTC, simonschwan commented on test/plugins/compare-numbers-plugin-test.js
> +  '= works as expected': function () {
done

2017-02-06 13:09 UTC, simonschwan commented on test/plugins/compare-numbers-plugin-test.js
> +  'throw an exception if not known operator': function () {
done

2017-02-06 13:09 UTC, simonschwan commented on docs/examples/pipes/day-of-month.md
> +
done

2017-02-06 21:07 UTC, jhuenges approved these changes

2017-02-06 21:08 UTC, merged