Feature 76 chatverlauf filterung
amos-ws16/amos-ws16-arrowjs pull request #89
Opened 2017-02-08 15:12 UTC by dn0912

Chatfilterung für
- user und array aus usern
- time intervall: startTime, endTime
- Dokumentation

2017-02-08 19:09 UTC, jhuenges commented
@fabian247 Sorry! Ich hab @oesse PR zu erst gemerged ... Kannst du da nochmal schnell drüber gehen?

2017-02-08 19:18 UTC, oesse requested changes
Da sind noch ein paar Sachen

2017-02-08 19:18 UTC, oesse commented on lib/plugins/chat-text-plugin.js
> +  let endTime = (params && params['endTime']) || 9999999999
Magic Numbers! Lieber eine Konstante `beginningOfTime` und `endOfTime`, die du dann auch explizit beim Filtern checkst.

2017-02-08 19:18 UTC, oesse commented on lib/plugins/chat-text-plugin.js
>    if ((e1 !== null) && (e1.constructor === Error)) {
Wenn `e1 !== null` (warum 1?) dann ist es auf jeden Fall ein Error, der auch eine Message hat. Und dieser tritt nur auf, wenn es den Pfad `chat[].text` in dem Objekt `finalTransChat` nicht gibt.

2017-02-08 19:18 UTC, oesse commented on lib/plugins/chat-text-plugin.js
> +  let intervallChat = utils.getChatMessagesInTimeInterval(chat, startTime, endTime)
Vielleicht besser: `intervallChat -> chatInInterval`

2017-02-08 19:18 UTC, oesse commented on lib/plugins/chat-text-plugin.js
> +  let finalTransChat = (user === '*' ? intervallChat : utils.getChatMessagesFromUsers(intervallChat, user))
Definitiv besser: `finalTransChat -> chatByUser`

2017-02-08 19:18 UTC, oesse commented on lib/utils.js
> +function getChatMessagesInTimeInterval (chatObject, startTime, endTime) {
`getChatMessagesInTimeInterval -> filterChatByTime`

2017-02-08 19:18 UTC, oesse commented on lib/utils.js
> +  isArray(chatObject.chat)
Da ist wohl vorher was durchs CR gerutscht. `isArray -> ensureArray`: Bei `isArray` erwartet man, dass ein true oder false zurück kommt und nicht ein Fehler geworfen wird, wenn es kein Array ist.

2017-02-08 19:18 UTC, oesse commented on lib/utils.js
> +  arrayNotEmpty(chatObject.chat)
dito `ensureArrayNotEmpty`

2017-02-08 19:18 UTC, oesse commented on lib/utils.js
> +  return {chat: transformedChat}
```javascript
const filteredMessages = chatObject.chat.filter(message => !message.ts || isInRange(message.ts, startTime, endTime))
return { chat: filteredMessages }
```

2017-02-08 19:18 UTC, oesse commented on lib/utils.js
> +  if (users.constructor !== Array) {
`if (Array.isArray(users))`

2017-02-08 19:18 UTC, oesse commented on lib/utils.js
> +  return {chat: transformedChat}
```javascript
const filtered = chatObject.chat.filter(message => users.indexOf(message.user) !== -1)
```

2017-02-08 20:38 UTC, jhuenges commented
ping @oesse

2017-02-08 20:46 UTC, oesse requested changes
Ein paar Sachen vom letzten CR vergessen

2017-02-08 20:46 UTC, oesse commented on lib/utils.js
> +  return transformedChat
Immernoch ein `chatObj.filter(...)`

2017-02-08 20:46 UTC, oesse commented on lib/utils.js
> +  return transformedChat
Immernoch ein `chatObj.filter(...)`

2017-02-08 20:46 UTC, oesse commented on lib/utils.js
> +function getChatMessagesFromUsers (chatObject, users) {
`filterByUser()`

2017-02-08 20:49 UTC, oesse requested changes

2017-02-08 20:49 UTC, oesse commented on lib/utils.js
> +  return filteredChat
`chatObj.filter(...)`

2017-02-08 20:49 UTC, oesse commented on lib/utils.js
> +  return filteredChat
`chatObject.filter(...)`

2017-02-13 07:38 UTC, jhuenges approved these changes

2017-02-13 09:41 UTC, oesse approved these changes

2017-02-13 16:23 UTC, merged